### ISSUE TITLE
learning-gateway 的application.yml中，http://10.17.0.19:3000，这个地址是做什么的

### ISSUE THREAD

**Issue by shikj** [citrucn/Learning#2]
globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: http://10.17.0.19:3000

**Comment by shikj** [comment]
您好，请问这个地址是做什么的

**Comment by Furinai** [comment]
跨域配置啊，这网上一搜答案很多
